"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/styles/global.css";
import { SessionProvider } from "next-auth/react";
import { AppStateProvider } from "@/context/MyContext";
import NavBar from "@/components/(main)/NavBar";
import SearchBar from "@/components/(main)/SearchBar";
import PlayTrack from "@/components/(main)/PlayTrack";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppStateProvider>
      <html lang="en">
        <head>
          <script src="https://sdk.scdn.co/spotify-player.js"></script>
        </head>
        <body className={inter.className}>
          <SessionProvider>
            <NavBar />
            <SearchBar />
            <PlayTrack />
            {children}
          </SessionProvider>
        </body>
      </html>
    </AppStateProvider>
  );
}
